[general]
import = ["~/.config/alacritty/themes/nightfox.toml"]
live_config_reload = true

[window]
startup_mode = "Maximized"
# opacity = 0.9

[font]
normal = { family = "FiraCode Nerd Font Propo", style = "Retina" }
size = 15

[env]
TERM = "xterm-256color" 
