require("core.plugins")
require("core.colors")
require("core.configs")
require("core.mappings")

require("plugins.mason")
require("plugins.mason_installer")
require("plugins.lsp")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.conform")
require("plugins.neotree")
require("plugins.cmp")
require("plugins.bufferline")
require("plugins.move")
require("plugins.pairs")
require("plugins.comment")
require("plugins.git-blame")
